name: Read and Upload Artifact

on:
  workflow_dispatch:

jobs:
  read_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read existing artifact or set default value
        id: read_artifact
        run: |
          if [ -f "artifact/data.txt" ]; then
            # 读取现有 artifact 中的数据
            data=$(cat artifact/data.txt)
          else
            # 设置默认值
            data="Default Value"
          fi
          echo "data=$data" >> $GITHUB_ENV


      - name: Use the data
        run: |
          echo "Using data:  ${{ env.data }}"

      - name: Save data to artifact
        run: |
          # 保存数据到 artifact
          echo ${{ env.data }} > artifact/data.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifact/data.txt
