name: Read and Upload Artifact

on:
  workflow_dispatch:

jobs:
  read_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2




      - name: Download result Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-result-artifact  # 要下载的Artifact的名称，与上面保存的名称对应
          path: .   # 下载后保存结果文件的目录
          
      - name: Use result from previous workflow
        run: |
          # 使用之前保存的结果文件
          cat ./result.txt
