name: Read and Upload Artifact

on:
  workflow_dispatch:

jobs:
  read_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate result
        run: |
          # 在这里生成结果，假设结果是存储在 result.txt 文件中
          echo "This is the result" > result.txt
          
      - name: Upload result as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-result-artifact  # Artifact的名称，你可以自定义
          path: result.txt          # 要上传的结果文件的路径


      - name: Download result Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-result-artifact  # 要下载的Artifact的名称，与上面保存的名称对应
          path: .   # 下载后保存结果文件的目录
          
      - name: Use result from previous workflow
        run: |
          # 使用之前保存的结果文件
          cat ./result.txt
