name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout sha
      uses: moonrailgun/branch-filestorage-action@v1.2.2
      with:
        path: sha
    - name: Read and show
      run: cat sha
    - name: update sha
      run: echo $(sha) > sha
