name: "mannual push image"
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: ''
        description: 'The branch name should be like *-x.x.x, for example release-1.0.0'
      repository_url:
        required: true
        default: 'aroundabout/'
        description: 'the repo name'
      image_url:
        required: true
        default: 'dandelionivy/'
        description: 'the docker images name'
      tag:
        required: true
        default: 'latest'
        description: 'the docker images tag'
      file:
        required: true
        default: './hugegraph-hubble/Dockerfile'
        description: 'the docker images tag'

jobs:
  build_latest:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ${{inputs.repository_url}}
      BRANCH: ${{inputs.branch}}
      TAG: ${{inputs.tag}}
      IMAGE_URL: ${{inputs.image_url}}
      FILE: ${{inputs.file}}
      
    steps:
    - name: Set image_url
      run: |
        image_url=${{env.IMAGE_URL}}:${{env.TAG}}
        echo $image_url && echo "IMAGE_URL=$image_url" >> $GITHUB_ENV
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - name: Checkout latest
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPOSITORY_URL }}
        ref: ${{ env.BRANCH }}
        fetch-depth: 2

    - name: Build X86 And Push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.FILE }}
        platforms: linux/amd64
        tags: ${{ env.IMAGE_URL }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
