name: Read Single Value from Artifacts

on:
  push:
    branches:
      - main

jobs:
  read_value:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts

      - name: Read value from file
        run: |
          cat my-artifacts/value.txt
